2018-09-02 05:08:00,302 INFO Database bulk load query started for: grant from filename: /home/development/Documents/Software/USPTO/CSV/CSV_G/grant_1982.csv
2018-09-02 05:08:00,654 ERROR Database bulk load query failed.../home/development/Documents/Software/USPTO/CSV/CSV_G/grant_1982.csv into table: uspto.GRANT
2018-09-02 05:08:00,655 ERROR Query string: COPY uspto.GRANT FROM STDIN DELIMITER '|' CSV HEADER
2018-09-02 05:08:00,655 ERROR Exception: <class 'psycopg2.DataError'> in Filename: SQLProcessor.py on Line: 94 Traceback: Traceback (most recent call last):
  File "/home/development/Documents/Software/USPTO/SQLProcessor.py", line 94, in load_csv_bulk_data
    self._cursor.copy_expert(sql, open(csv_file['csv_file_name'], "r"))
DataError: invalid input syntax for integer: "3.5"
CONTEXT:  COPY grant, line 1261, column grantlength: "3.5"


4450705 int_class malformed

2018-09-04 13:31:16,356 INFO Database bulk load query started for: applicant from filename: /home/development/Documents/Software/USPTO/CSV/CSV_G/applicant_ipgb20150428_wk17.csv
2018-09-04 13:31:16,565 ERROR Database bulk load query failed.../home/development/Documents/Software/USPTO/CSV/CSV_G/applicant_ipgb20150428_wk17.csv into table: uspto.APPLICANT_G
2018-09-04 13:31:16,566 ERROR Query string: COPY uspto.APPLICANT_G FROM STDIN DELIMITER '|' CSV HEADER
2018-09-04 13:31:16,593 ERROR Exception: <class 'psycopg2.IntegrityError'> in Filename: SQLProcessor.py on Line: 94 Traceback: Traceback (most recent call last):
  File "/home/development/Documents/Software/USPTO/SQLProcessor.py", line 94, in load_csv_bulk_data
    self._cursor.copy_expert(sql, open(csv_file['csv_file_name'], "r"))
IntegrityError: duplicate key value violates unique constraint "applicant_g_pkey"
DETAIL:  Key (grantid, "position", filename)=(9018354, 6, ipgb20150428_wk17) already exists.
CONTEXT:  COPY applicant_g, line 6089

2018-09-04 13:32:04,409 ERROR Database bulk load query failed.../home/development/Documents/Software/USPTO/CSV/CSV_G/applicant_ipgb20150421_wk16.csv into table: uspto.APPLICANT_G
2018-09-04 13:32:04,409 ERROR Query string: COPY uspto.APPLICANT_G FROM STDIN DELIMITER '|' CSV HEADER
2018-09-04 13:32:04,410 ERROR Exception: <class 'psycopg2.IntegrityError'> in Filename: SQLProcessor.py on Line: 94 Traceback: Traceback (most recent call last):
  File "/home/development/Documents/Software/USPTO/SQLProcessor.py", line 94, in load_csv_bulk_data
    self._cursor.copy_expert(sql, open(csv_file['csv_file_name'], "r"))
IntegrityError: duplicate key value violates unique constraint "applicant_g_pkey"
DETAIL:  Key (grantid, "position", filename)=(RE045474, 13, ipgb20150421_wk16) already exists.
CONTEXT:  COPY applicant_g, line 782
